# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20160224_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'storage_vats'),
        ),
    ]
