# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_containertype_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertype',
            name='slot_type',
        ),
    ]
