# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_containertype_slot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containersupertype',
            name='has_children',
        ),
    ]
