# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_containersupertype_has_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockable',
            field=models.IntegerField(),
        ),
    ]
