# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_stockable_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockableType',
        ),
    ]
