# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_delete_stockabletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='notes',
            field=models.CharField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="http://www.darkcoding.net/software/markdown-quick-reference">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. For subscripts: H~2~0. For superscripts: 6.02 x 10^23^.', max_length=200),
        ),
    ]
