# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20160301_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['parent__id', 'horizontal_position', 'vertical_position']},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='container',
            name='is_thawed',
            field=models.BooleanField(default=False, help_text=b'Check this if this is a tube that was thawed, or another type of container that was removed'),
        ),
        migrations.AlterField(
            model_name='container',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='container',
            name='stock',
            field=models.ForeignKey(blank=True, help_text=b'If this container is a tube or well, it might hold a stock', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Stock'),
        ),
        migrations.AlterField(
            model_name='container',
            name='thawed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
