# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0002_auto_20160224_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vector',
            options={'ordering': ['id']},
        ),
    ]
