# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharea',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
