# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_researcharea_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researcharea',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'research area blurbs'},
        ),
        migrations.AddField(
            model_name='researcharea',
            name='html_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
