# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160224_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinlabsection',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
