# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160224_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'lab member positions'},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='name',
        ),
    ]
