# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160224_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_filename',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.URLField(blank=True, help_text=b'Your public profile will redirect here if your blurb is empty.', verbose_name=b'Personal website URL'),
        ),
    ]
