# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160224_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
