# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160224_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='pubmed_id',
            new_name='pmid',
        ),
        migrations.AddField(
            model_name='publication',
            name='pmcid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
