# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160225_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-pmid']},
        ),
        migrations.AlterField(
            model_name='publication',
            name='pmcid',
            field=models.CharField(blank=True, max_length=20, verbose_name=b'PMCID'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pmid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'PMID'),
        ),
    ]
