# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160225_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'resource_logos'),
        ),
    ]
