# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_resource_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='logo_filename',
        ),
    ]
