# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_resource_logo_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='date',
            new_name='date_on_pubmed',
        ),
    ]
