# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160229_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='date_on_pubmed',
            new_name='issue',
        ),
    ]
