# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_auto_20160224_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocol',
            old_name='title_url',
            new_name='slug',
        ),
    ]
