# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_auto_20160225_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='title',
            field=models.CharField(help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="http://www.darkcoding.net/software/markdown-quick-reference">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. For subscripts: H~2~0. For superscripts: 6.02 x 10^23^.', max_length=250),
        ),
    ]
