# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0008_auto_20160225_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='author',
            field=models.ForeignKey(blank=True, help_text=b'If none selected, defaults to logged in user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='slug',
            field=models.SlugField(help_text=b"This is for the protocol's URL", max_length=120, unique=True),
        ),
    ]
