# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worm_strains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transgene',
            name='vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vectors.Vector'),
        ),
        migrations.AlterField(
            model_name='wormstrain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wormstrain',
            name='mutagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worm_strains.Mutagen'),
        ),
        migrations.AlterField(
            model_name='wormstrain',
            name='parent_strain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worm_strains.WormStrain'),
        ),
        migrations.AlterField(
            model_name='wormstrain',
            name='transgene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worm_strains.Transgene'),
        ),
        migrations.AlterField(
            model_name='wormstrainline',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
