# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worm_strains', '0002_auto_20160224_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutagen',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='mutagen',
            old_name='mutagen',
            new_name='name',
        ),
    ]
