# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worm_strains', '0004_auto_20160226_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wormstrainline',
            name='id',
        ),
        migrations.AlterField(
            model_name='wormstrainline',
            name='stockable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='storage.Stockable'),
        ),
    ]
