# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worm_strains', '0005_auto_20160229_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wormstrainline',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='wormstrainline',
            name='stockable',
        ),
        migrations.RemoveField(
            model_name='wormstrainline',
            name='strain',
        ),
        migrations.DeleteModel(
            name='WormStrainLine',
        ),
    ]
