# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20160229_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worm_strains', '0006_auto_20160229_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='WormStrainLine',
            fields=[
                ('stockable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.Stockable')),
                ('created_internally', models.BooleanField(default=False)),
                ('times_outcrossed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('received_from', models.CharField(blank=True, max_length=100)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text=b'Use Markdown syntax for italics, bullets, etc. See <a href="http://www.darkcoding.net/software/markdown-quick-reference">a quick reference</a>, <a href="http://www.markdowntutorial.com/">a tutorial</a>, or practice <a href="http://dillinger.io/">here</a>. For subscripts: H~2~0. For superscripts: 6.02 x 10^23^.')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worm_strains.WormStrain')),
            ],
            options={
                'ordering': ['strain__name'],
            },
            bases=('storage.stockable',),
        ),
    ]
