# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worm_strains', '0007_wormstrainline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormstrain',
            name='genotype',
            field=models.CharField(max_length=500),
        ),
    ]
