# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worm_strains', '0008_auto_20160302_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wormstrain',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wormstrainline',
            options={'ordering': ['strain__id']},
        ),
        migrations.RenameField(
            model_name='wormstrain',
            old_name='name',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='wormstrain',
            name='genotype',
            field=models.CharField(help_text=b'If a precise genotype is unavailable or not easily written, put something meaningful about what the strain is -- e.g. "suppressor of X". If no information is available, put "n/a"', max_length=500),
        ),
        migrations.AlterField(
            model_name='wormstrain',
            name='parent_strain',
            field=models.ForeignKey(blank=True, help_text=b'Worm strain that this strain was made from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='worm_strains.WormStrain'),
        ),
        migrations.AlterField(
            model_name='wormstrainline',
            name='created_internally',
            field=models.BooleanField(default=False, help_text=b"Check if this line was created in our lab. In this case you probably won't fill in the fields below about receipt."),
        ),
    ]
