# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worm_strains', '0010_auto_20160303_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wormstrain',
            name='id',
            field=models.CharField(help_text=b'Since this is the primary key it cannot be edited once saved. If you need to edit it, please do so in the database directly. You will need to edit the worm strain field for any corresponding worm strain lines as well, turning off foreign key constrains while editing.', max_length=30, primary_key=True, serialize=False),
        ),
    ]
